### ISSUE TITLE
separate sessions and permissions

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/PermissionManager#177]
# Bug report
Sorry if this is a repost.. but i couldn't find the answer in all the closed issues.

Im trying to use Separate session for users and admins.. i've done all the steps in the guide and managed to make it work.. BUT i cant use blade directives like @can('user_permission') in my files..
i do have admin role for the Backpack User Model in the db as well.

### Backpack, Laravel, PHP, DB version:
"php": "^7.1.3",
"backpack/crud": "^3.4",
"backpack/permissionmanager": "^3.12",
"laravel/framework": "5.7.*",

**Comment by tabacitu** [comment]
Hi @mpixelz ,

It’s a known issue - already fixed in the upcoming upgrade, which will be launched this week. It’s a breaking change unfortunately.

That’s most likely because you’re using different ```User``` models for authentication and permissions. Make sure all models extend the same ```App\User``` model, where you’ve used the roles and permissions trait. So:
- in ```config/backpack/base.php``` you have ```user_model_fqn``` pointing to ```App\User::class```;
- in ```config/auth.php``` you have ```providers.users.model``` pointing to ```App\User::class```;

This will fix the ```@can``` statements for you, but will unfortunately break the “recover password” functionality. To fix that one too, please implement everything inside the ```BackpackUser``` class into your own ```User``` model.

Sorry it’s such a tough fix - we found no way to fix this without a breaking change, so had to wait until we launch 3.5 - again, later this week.

Cheers!

PS. Alternatively, if you’re using different models for Users and Admins, make sure the Admin model [uses this trait](https://github.com/tightenco/parental) after it extends the User model. For some reason, Eloquent models DO NOT inherit relationships - this trait fixes that.

**Comment by mpixelz** [comment]
i just started testing this on a new laravel installation with backpack base 1 and crud 3.5
followed everything as per the document..
in my config/backpack/base.php i have
```
// Fully qualified namespace of the User model
    'user_model_fqn' => App\Models\BackpackUser::class,
// The guard that protects the Backpack admin panel.
    // If null, the config.auth.defaults.guard value will be used.
    'guard' => 'backpack',

    // The password reset configuration for Backpack.
    // If null, the config.auth.defaults.passwords value will be used.
    'passwords' => 'backpack',
```
and in my config/auth.php i have 
```
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\BackpackUser::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```
but still cant use the @can statements. I do have App\Models\BackpackUser class as well.. which extends the User::class but still wont work. what am i missing here?

**Comment by tabacitu** [comment]
Hi @mpixelz ,

On the ```User``` model that ```BackpackUser``` extends, do you have 
- ```use HasRoles;```  
- (or)
- ```use Spatie\Permission\Traits\HasRoles;``` 

?

**Comment by mpixelz** [comment]
@tabacitu Yes i do. 
They worked when i was using just the single session. 

Used the exact installation instruction as in the read me to the T.

**Comment by tabacitu** [comment]
Hmm... ok, thank you. On it!

**Comment by tabacitu** [comment]
@tomsb also mentioned this in an email:

>As of backapck 3.5, we can't use auth() anywhere in admin panel, right?
>This breaks things like ```@role()``` from PermissionManager, because this blade directive checks role like this:
>```... if(auth({$guard})->check() && ...```
>It's using ```auth()```, not ```backpack_auth()``` - and this is not working as expected.
>
>This thing will break any other package which is using ```auth()``` instead of ```backpack_auth()```... Am I right?
>And what should we do to fix this?

Let's continue the conversation about this topic here, please, since we already have an issue open.

**Comment by tabacitu** [comment]
@mpixelz until we find a proper solution, **if you're only using the Backpack authentication** (no separate auth for users), you can change this in your ```config/auth.php``` to make it work:

```diff

    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    'defaults' => [
-       'guard'     => 'web',
+       'guard'     => 'backpack',
        'passwords' => 'users',
    ],
```

**Comment by tabacitu** [comment]
But if you _do_ have separate auth for users, this _will_ stop ```@can``` from working on the user side. Currently investigating a proper solution.

**Comment by mpixelz** [comment]
i do have separate auth for admin and user. looks like i'll have to wait for a proper solution then 👍

**Comment by tabacitu** [comment]
Ok, I understand. 

Note that ```if (backpack_user()->can('read'))``` works ALL THE TIME, it's only the ```@can``` directive that spatie/laravel-permission uses, that doesn't work in the admin panel. So if you can, you can replace:

```php
@can('read')
@endcan
```

with

```php
@if(backpack_user()->can('read'))
@endif
```

The problem is that the ```@can``` directive uses the default Laravel guard, and _only_ the default Laravel guard.

**Comment by tabacitu** [comment]
Solutions I found so far:

### Option A

Having a ```backpack_can()``` helper, but... it seems like yet another Laravel method we're duplicating because some bit of Laravel doesn't allow customization... I don't really like this...

### Option B

```php
        config()->set('auth.defaults.guard', 'backpack');
```

in all constructors in the admin panel, but... this is kind of a hack... We could make it more general by having everything extend a controller that has this, but... we'd also need to instruct people to do this for the admin controllers they create / generate / etc...

### Option C

Having this inside the BaseServiceProvider:
```php
        $this->app['router']->matched(function (\Illuminate\Routing\Events\RouteMatched $e) {
            $route = $e->route;
            if (!array_has($route->getAction(), 'guard')) {
                return;
            }
            $routeGuard = array_get($route->getAction(), 'guard');
            $this->app['auth']->resolveUsersUsing(function ($guard = null) use ($routeGuard) {
                return $this->app['auth']->guard($routeGuard)->user();
            });
            $this->app['auth']->setDefaultDriver($routeGuard);
        });
```
would allow us to specify a custom ```guard``` on any route group, and ```Auth``` will use that guard for all routes within that route group, instead of the default Laravel guard. We could push the fix inside our Base and CRUD packages, and instruct people to do it in their ```routes/backpack/custom.php``` in the upgrade guide:
```diff
<?php

// --------------------------
// Custom Backpack Routes
// --------------------------
// This route file is loaded automatically by Backpack\Base.
// Routes you generate using Backpack\Generators will be placed here.

Route::get('api/article', 'App\Http\Controllers\Api\ArticleController@index');
Route::get('api/article-search', 'App\Http\Controllers\Api\ArticleController@search');
Route::get('api/article/{id}', 'App\Http\Controllers\Api\ArticleController@show');

Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
+   'guard'      => config('backpack.base.guard'),
    'middleware' => ['web', config('backpack.base.middleware_key', 'admin')],
    'namespace'  => 'App\Http\Controllers\Admin',
], function () { // custom admin routes
    // CRUD resources and other admin routes
    CRUD::resource('monster', 'MonsterCrudController');
    CRUD::resource('icon', 'IconCrudController');
    CRUD::resource('product', 'ProductCrudController');
}); // this should be the absolute last line of this file
```

This last option has the added benefit that it will also:
- allow us to use ```Auth::user()```, ```Auth::check()``` and ```auth()->user()->id``` inside the admin panels, and it will return the logged in _admin_ user, using the custom guard (```backpack```);
- eliminate the need for ```backpack_user()``` and ```backpack_auth()```;
- make _old_ form request files, which use ```Auth::check()``` instead of ```backpack_auth->check()``` work, just like that;

However, **this _could_ be counter-intuitive**. When someone types ```Auth::user()``` inside the ```dashboard.blade.php``` file, for example, do they _understand_ that they're using the ```backpack``` guard? I think so, but... let me know...

So far Option C looks like the best solution, by far... Just worried that it might be _weird_ that ```Auth``` inside the admin panel uses the ```backpack``` guard, and outside it uses the default Laravel guard... Thoughts?

Cheers!

**Comment by tabacitu** [comment]
Also, what if people were using both ```auth()``` and ```backpack_auth()``` in the same admin panel context? For example, to test if an admin was logged as both a user and an admin? 

This would break it for them because both would return the same thing, if we force Auth to use the ```backpack``` guard on admin panel routes...

**Comment by tomsb** [comment]
I think there's no problem for backpack to use a `backpack` guard on all the admin routes. And that implies  `auth()` inside backpack routes is using the `backpack` guard.

I like option C the best.

**Comment by tabacitu** [comment]
Ok so I slept on it :-) And I think I've figured out a few solutions that have the same result as C, but do it in a different place. I'm not in love with C because:
- we're basically overwriting a Laravel functionality - if they ever decide to support ```guard``` we'll definitely be conflicting with their implementation;
- it requires users who have already installed 3.5 to make changes to their "routes/backpack/custom.php``` file;
- it isn't clean; we're doing something in the BaseServiceProvider (a package) that applies to routing and middleware... but only if a certain extra property is defined... it smells...

Here are two more options below, both of them (I think) are better than C.

### Option D

We add this  to ```CheckIfAdmin::handle()```:
```php
        app('auth')->setDefaultDriver(config('backpack.base.guard'));
```
The downside would be that:
- CheckIfAdmin would do two things then, not only checking if it's an admin but also overwriting the guard;
- since people who have installed 3.5 already have already published CheckIfAdmin in their projects, they wouldn't benefit from this update;

### Option E

We create a new middleware:
```php
<?php

namespace Backpack\Base\app\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;

class UseBackpackAuthGuardInsteadOfDefaultAuthGuard
{
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure                 $next
     * @param string|null              $guard
     *
     * @return mixed
     */
    public function handle($request, Closure $next, $guard = null)
    {
        app('auth')->setDefaultDriver(config('backpack.base.guard'));
    }
}
```

And we use this one by default too, just like CheckIfAdmin. 

The downside:
- people who have already installed 3.5 will not get the update, unless they manually add this to their ```config/backpack/base.php``` file:

```diff

    // The classes for the middleware to check if the visitor is an admin
    // Can be a single class or an array of clases
    'middleware_class' => [
        App\Http\Middleware\CheckIfAdmin::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
+       Backpack\Base\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class,
    ],
```

The upside:
- developers can _easily_  comment that line in new projects, and have Auth use the default guard;

---

I think we have a winner here :-) Option E. @mpixelz , @tomsb am I right or am I right? I'll put a PR together ASAP.
