### ISSUE TITLE
[Known Issue] @can() helper doesn't work like backpack_user()->hasPermission() because of different guards

### ISSUE THREAD

**Issue by tmtung144** [Laravel-Backpack/PermissionManager#193]
# Bug report

### What I did:
This is Roles
![image](https://user-images.githubusercontent.com/19670776/57762850-719da780-772a-11e9-9f53-c30a1a580fae.png)
and this is Permissions
![image](https://user-images.githubusercontent.com/19670776/57762881-7f532d00-772a-11e9-9098-e7b7b236581b.png)

I have done the installation as instructed and have read both the instructions https://github.com/Laravel-Backpack/PermissionManager and https://github.com/spatie/laravel-permission

As in the second image, my user has full administrator rights (view, create, update, delete) and other rights (log, backup ...) but when I use `@can` in blade or` ['permission:backup']` or `[' role_or_permission:administrator|backup']` in routes, they cannot distinguish the permissions I have granted to users. Why so?

### What I expected to happen:
@can or backpack_user()->hasDirectPermission('backup') will work and similar in **middleware**

### What happened:
- `{{ dd(backpack_user()->hasDirectPermission('backup')) }}` --> There is no permission named `backup` for guard `backpack` ---- default guard = 'web'
- @can in ..\resources\views\vendor\backpack\base\inc\sidebar_content.blade.php --> Hide authorized menus
```
'route' => [
        'prefix'     => config('backpack.base.route_prefix', 'admin').'/elfinder',
        'middleware' => ['web', config('backpack.base.middleware_key', 'admin'), 'permission:filemanager'], 
    ]
```
in ..\config\elfinder.php ---> ERROR 403 Forbidden. User is not logged in.

### What I've already tried to fix it:
Some things still work in the controller, for example:

```
if (!backpack_user()->getAllPermissions()->contains(Permission::findByName('view'))) {
            $this->crud->denyAccess('list');
        }

        if (backpack_user()->getAllPermissions()->contains(Permission::findByName('delete'))) {
            $this->crud->enableBulkActions();
            $this->crud->addBulkDeleteButton();
        } else {
            $this->crud->removeButton('delete');
        }

        if (!backpack_user()->getAllPermissions()->contains(Permission::findByName('create'))) {
            $this->crud->removeButton('create');
        }

        if (backpack_user()->getAllPermissions()->contains(Permission::findByName('update'))) {
            $this->crud->allowAccess('revisions');
            $this->crud->with('revisionHistory');
        } else {
            $this->crud->removeButton('update');
            $this->crud->allowAccess('show');
        }
```

**Comment by tmtung144** [comment]
I had to rewrite the routeMiddleware as follows:

`php artisan make:middleware Permission`

```
<?php

namespace App\Http\Middleware;

use Closure;
use Spatie\Permission\Exceptions\UnauthorizedException;

class Permission
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next, $permission)
    {
        if (!backpack_auth()) {
            throw UnauthorizedException::notLoggedIn();
        }

        $permissions = is_array($permission)
            ? $permission
            : explode('|', $permission);

        foreach ($permissions as $permission) {
            if (backpack_user()->getAllPermissions()->contains(\Backpack\PermissionManager\app\Models\Permission::findByName($permission))) {
                return $next($request);
            }
        }

        throw UnauthorizedException::forPermissions($permissions);
    }
}

```

and replace the following line in **$routeMiddleware** `...\app\Http\Kernel.php`

`'permission' => \App\Http\Middleware\Permission::class,`

**Comment by ArroWsGM** [comment]
@tmtung144 
Had the same issue with roles, your workaround works fine, except one thing: if you on the guarded route, role|hasrole|can etc. blade directives also stops working. Any way, ``@if(backpack_user()->hasRole('somerole'))`` works fine.

**Comment by tmtung144** [comment]
I am not sure if **PermissionManager** can work with **Super Admin** and all of my routes check for protection by rights rather than checking roles.
If there are any additional things you want to contribute, I can apply it to my projects. thank you

**Comment by simonecicognani** [comment]
https://github.com/spatie/laravel-permission/issues/1173

**Comment by tabacitu** [comment]
I think the root of the problem might be that Backpack is using a different model for login, ```BackpackUser```, and for some time now Spatie/Laravel-permission also stores that in the db and puts the permission on the ```BackpackUser``` or ```User``` model.

If so, eliminating the ```BackpackUser``` model from Backpack v4 should fix it. I've added an issue here for it here - https://github.com/Laravel-Backpack/Base/issues/399 - please pitch in with your opinion if you're for/against this.

Personally I've fallen out of love with spatie/permission-manager, and I'm thinking of using [Bouncer](https://github.com/JosephSilber/bouncer) for my next projects. Too bad nobody created a Backpack package to manage Bouncer users yet :-)

**Comment by ArroWsGM** [comment]
@tabacitu, no I think it's rather a guard problem. If you do not use the default 'web' guard, permission package pick the wrong one, and you need to explicitly define it:

`$this->request->user(config('app.guard', 'web'));`
or
`$this->user->hasPermissionTo('delete-other-files', config('app.guard', 'web'));`

I have a ton of those nasty strings in my current project.

**Comment by tabacitu** [comment]
Ugh.... even worse... I know their intentions were good when adding this, but I think in 99% of all apps, developers DON'T want their permissions or roles to be guard-specific.

That's how it was when this project first started, and I think it was perfect for the large majority of people. If anybody needed extra complexity, they added it themselves. [It is said](https://github.com/spatie/laravel-permission/issues/1156#issuecomment-512887934) that spatie/laravel-permission v3 will be coming in a few months, and that it'll be guard-agnostic.

I'm not sure wether we should wait for v3, or move to Bouncer...

**Comment by drbyte** [comment]
@tabacitu If the Spatie package were to default to picking the current guard from the `config` array, instead of preferring the Model's defined guard as it does now, would that solve these problems?

**Comment by juventus18** [comment]
I'm a "no" vote for Bouncer. Mainly because I don't really like all the static calls or the language used (i.e. "abilities" instead of "permissions". If another dev comes in and sees "abilities" everywhere that concept will need more mental effort than seeing "permissions" even though they are actually the same. also weird alias methods for no real reason.. (What if i need to refactor? I now have to refactor 2x...) 
```
Bouncer::is($user)->notA('moderator');
Bouncer::is($user)->notAn('admin');
```
Bouncer seems like its trying to "change the paradigm" of something that is a very solid and well-understood concept anyway, with no real visible benefit.

**Comment by tabacitu** [comment]
@drbyte I don't think that would fix it either, no. Backpack's guard is not the default. It's just the one used by Backpack. We _could_ instruct people to make it the default, though. If they use PermissionManager.

**Comment by itelmenko** [comment]
Look like I have same problem.

Debug code in view:
```
{{'list: '.json_encode(backpack_user()->getAllPermissions()->all())}}
{{'can: '.json_encode(backpack_user()->can("permissions"))}}
```

Result:

```
list: [{"id":1,"name":"permissions","guard_name":"web","created_at":"2019-10-15 13:56:28","updated_at":"2019-10-15 13:56:28","pivot":{"model_id":1,"permission_id":1,"model_type":"App\\Models\\BackpackUser"}}]
can: false
```

**Comment by simonecicognani** [comment]
> Look like I have same problem.
> 
> Debug code in view:
> 
> ```
> {{'list: '.json_encode(backpack_user()->getAllPermissions()->all())}}
> {{'can: '.json_encode(backpack_user()->can("permissions"))}}
> ```
> 
> Result:
> 
> ```
> list: [{"id":1,"name":"permissions","guard_name":"web","created_at":"2019-10-15 13:56:28","updated_at":"2019-10-15 13:56:28","pivot":{"model_id":1,"permission_id":1,"model_type":"App\\Models\\BackpackUser"}}]
> can: false
> ```

https://github.com/spatie/laravel-permission/issues/1173#issuecomment-519408514

**Comment by ziming** [comment]
I just did Bouncer with Backpack in a project. It is pretty nice. @tabacitu 

I don't think I will have the time to learn to write a Bouncer package for backpack this year. But I may write an article on it this year for those who would like a reference implementation.

**Comment by ziming** [comment]
Article written. Hope it helps.

https://qiita.com/ziming/items/93c6b1bb43c27e33e39f

**Comment by rUriarteDev** [comment]
I was trying to use Backpack PermissionManager, but some errors began to appear, for example:
`if (backpack_user () -> hasPermissionTo ('listComedor'))`
throws the following error: 
`There is no permission named `listComedor` for guard` backpack`.`
From what was read in the previous comments, the package could not be used currently, or is there any way to correct these errors? laravel/spatie could not be used too for the same reasons?
Cheers

**Comment by pxpm** [comment]
@rUriarteDev it might be with the permission create. How do you create your permission on database? 

You have to pass the correct guard in item creation. Also, in user model make sure it is using the backpack_guard() !

Best,
Pedro

**Comment by rUriarteDev** [comment]
Hi @pxpm thank you for responding so quickly, I have checked my permissions table and the permission is actually created with the "web" guard. I am using the package interface to create the permissions, I would not have to create them with the "backpack" guard, is there a way to change this or should I create the permissions in another way. Where can I check that the user model is using the backpack_guard ()
Thank you very much in advance
![image](https://user-images.githubusercontent.com/39219144/70391881-a91abc80-19b8-11ea-9c91-da61eecd4743.png)
![image](https://user-images.githubusercontent.com/39219144/70391873-92746580-19b8-11ea-9d48-60617ceec748.png)

**Comment by rUriarteDev** [comment]
The first solution i found is to set 'multiple_guards' => true, in permissionmanager.php. Then set all my roles and permissions with 'backpack' guard. I dont know if this is the best solution, what do you think @pxpm ? This would not break some system functionality?
![image](https://user-images.githubusercontent.com/39219144/70392821-74136780-19c2-11ea-8b02-a3b1aa115cce.png)

**Comment by ajgentile** [comment]
> I think the root of the problem might be that Backpack is using a different model for login, `BackpackUser`, and for some time now Spatie/Laravel-permission also stores that in the db and puts the permission on the `BackpackUser` or `User` model.
> 
> If so, eliminating the `BackpackUser` model from Backpack v4 should fix it. I've added an issue here for it here - https://github.com/Laravel-Backpack/Base/issues/399 - please pitch in with your opinion if you're for/against this.
> 
> Personally I've fallen out of love with spatie/permission-manager, and I'm thinking of using [Bouncer](https://github.com/JosephSilber/bouncer) for my next projects. Too bad nobody created a Backpack package to manage Bouncer users yet :-)

I'm using Bouncer, but integrated it manually. I'll post my code. Maybe it will be useful to someone.

**Comment by drbyte** [comment]
@drbyte wrote:
> @tabacitu If the Spatie package were to default to picking the current guard from the `config` array, instead of preferring the Model's defined guard as it does now, would that solve these problems?

@tabacitu wrote:
> @drbyte I don't think that would fix it either, no. Backpack's guard is not the default. It's just the one used by Backpack. We _could_ instruct people to make it the default, though. If they use PermissionManager.

@tabacitu Will https://github.com/spatie/laravel-permission/pull/1384 fix this? Will it create any problems with Backpack?

**Comment by tabacitu** [comment]
@drbyte - I think it would solve the problem, yes! I don't see why it would create any problems, just solutions 😆 I'd love to see that merged.

**Comment by drbyte** [comment]
@tabacitu Will it cause your Backpack users great grief if I tag it as a 4.0 release?

**Comment by tabacitu** [comment]
Haha. No - go ahead. Breaking changes require a version bump, everybody should understand that. 

Plus, with Laravel 7 coming out in a few days, it's a good opportunity for people to upgrade ALL their dependencies. If an upgrade guide is necessary, and it's half as good as the [excellent list of changes](https://github.com/spatie/laravel-permission/releases) you've done for 3.9.0, I think people will have zero reasons to be upset.

Thanks for asking though! Very kind of you.

**Comment by tabacitu** [comment]
I've just updated the readme to specify two ways to work around this limitation, inside ```config/backpack/base.php```:

**Option A. Use the ```web``` middleware everywhere (including inside the admin panel)**

```diff
    // The guard that protects the Backpack admin panel.
    // If null, the config.auth.defaults.guard value will be used.
-   'guard' => 'backpack',
+   'guard' => null,
```

The roles and permissions you add from the admin panel will have ```guard = web``` in the db.
```can()``` statements will work because they use the ```web``` (or current) guard by default.

**Option B. Use the ```backpack``` middleware**

```diff
    // The classes for the middleware to check if the visitor is an admin
    // Can be a single class or an array of clases
    'middleware_class' => [
        App\Http\Middleware\CheckIfAdmin::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
+       \Backpack\CRUD\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class,
    ],
```

The roles and permissions you add from the admin panel will have ```guard = backpack``` in the db.
```can()``` statements will work because the default guard inside Backpack routes is now ```backpack```.

---

Since we have two workaround for this, and they're both documented, I'm going to close the issue.

**Comment by virginialloyd** [comment]
well.. i posted on gitter.. no answer..
posted on stackoverflow https://stackoverflow.com/questions/57143878/laravel-backpack-permission-seeding-role-does-not-exist .. no answer..

just recently caught up to this.. still broken..

**Comment by tabacitu** [comment]
Hi @virginialloyd ,

Sorry for the bad experience. This is a known issue with this package, but there's not much can do about it - your issue with the ```@can``` helper is not under our control, because it's not a feature of this package, but a feature of the underlying spatie/laravel-permission package.

A solution is in the works in https://github.com/spatie/laravel-permission/pull/1384 but until that gets merged and tagged, there's nothing we can do about this.

Until then, I've documented the workarounds in [my comment above](https://github.com/Laravel-Backpack/PermissionManager/issues/193#issuecomment-593301818) and in the docs. Please take a look.

Cheers!

**Comment by anasred** [comment]
I think you can instruct **"PermissionManager"** to add the following to User.php model

```public $guard_name = 'backpack';```

which will be used by Spatie before reading the "auth.guards" as per this link:
[https://docs.spatie.be/laravel-permission/v3/basic-usage/multiple-guards/#using-permissions-and-roles-with-multiple-guards](https://docs.spatie.be/laravel-permission/v3/basic-usage/multiple-guards/#using-permissions-and-roles-with-multiple-guards)
which stating this:
>Note: When determining whether a role/permission is valid on a given model, it checks against the first matching guard in this order (it does NOT check role/permission for EACH possibility, just the first match): - first the guardName() method if it exists on the model; - then the **$guard_name property** if it exists on the model; - then the first-defined guard/provider combination in the auth.guards config array that matches the logged-in user’s guard; - then the auth.defaults.guard config (which is the user’s guard if they are logged in, else the default in the file).

Notes:
* Make sure the ```'guard'``` key is = ```'backpack'``` in ```base.php``` like so:
```'guard' => 'backpack',```
* Make sure you reset the ```config/auth.php``` back to default if you add any modifications to it:
```    
'guards' => [
    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],

    'api' => [
        'driver' => 'token',
        'provider' => 'users',
        'hash' => false,
    ],
],
```

**Comment by tabacitu** [comment]
Huh - I didn't know you can do that, thanks @anasred . But... wouldn't that also force it to use the `backpack` guard on the front-end? The `User` would definitely be used on the front-end too, not only the admin panel...
